/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TeamPortalRouteImport } from './routes/team-portal'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiUploadCertificationRouteImport } from './routes/api/upload-certification'
import { Route as CareersIndexRouteImport } from './routes/careers.index'
import { Route as CareersApplyRouteImport } from './routes/careers.apply'
import { Route as FilesSplatRouteImport } from './routes/files.$'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesDayProgramRouteImport } from './routes/services.day-program'
import { Route as ServicesResidentialRouteImport } from './routes/services.residential'
import { Route as ServicesSupportedLivingRouteImport } from './routes/services.supported-living'
import { Route as TeamPortalIndexRouteImport } from './routes/team-portal.index'
import { Route as TeamPortalSetPasswordRouteImport } from './routes/team-portal.set-password'
import { Route as AuthenticatedTeamPortalAccountRouteImport } from './routes/_authenticated/team-portal.account'
import { Route as AuthenticatedTeamPortalAdminRouteImport } from './routes/_authenticated/team-portal.admin'
import { Route as AuthenticatedTeamPortalApplicantsRouteImport } from './routes/_authenticated/team-portal.applicants'
import { Route as AuthenticatedTeamPortalClientsRouteImport } from './routes/_authenticated/team-portal.clients'
import { Route as AuthenticatedTeamPortalCorporateRouteImport } from './routes/_authenticated/team-portal.corporate'
import { Route as AuthenticatedTeamPortalDashboardRouteImport } from './routes/_authenticated/team-portal.dashboard'
import { Route as AuthenticatedTeamPortalReportsRouteImport } from './routes/_authenticated/team-portal.reports'
import { Route as AuthenticatedTeamPortalSettingsRouteImport } from './routes/_authenticated/team-portal.settings'
import { Route as AuthenticatedTeamPortalTeamRouteImport } from './routes/_authenticated/team-portal.team'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthSetPasswordRouteImport } from './routes/api/auth/set-password'
import { Route as ApiAuthSignInRouteImport } from './routes/api/auth/sign-in'
import { Route as ApiAuthSignOutRouteImport } from './routes/api/auth/sign-out'
import { Route as AuthenticatedTeamPortalSettingsUsersRouteImport } from './routes/_authenticated/team-portal.settings.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamPortalRoute = TeamPortalRouteImport.update({
  id: '/team-portal',
  path: '/team-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadCertificationRoute = ApiUploadCertificationRouteImport.update({
  id: '/api/upload-certification',
  path: '/api/upload-certification',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CareersRoute,
} as any)
const CareersApplyRoute = CareersApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => CareersRoute,
} as any)
const FilesSplatRoute = FilesSplatRouteImport.update({
  id: '/files/$',
  path: '/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesDayProgramRoute = ServicesDayProgramRouteImport.update({
  id: '/day-program',
  path: '/day-program',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesResidentialRoute = ServicesResidentialRouteImport.update({
  id: '/residential',
  path: '/residential',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSupportedLivingRoute = ServicesSupportedLivingRouteImport.update({
  id: '/supported-living',
  path: '/supported-living',
  getParentRoute: () => ServicesRoute,
} as any)
const TeamPortalIndexRoute = TeamPortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamPortalRoute,
} as any)
const TeamPortalSetPasswordRoute = TeamPortalSetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => TeamPortalRoute,
} as any)
const AuthenticatedTeamPortalAccountRoute =
  AuthenticatedTeamPortalAccountRouteImport.update({
    id: '/team-portal/account',
    path: '/team-portal/account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamPortalAdminRoute =
  AuthenticatedTeamPortalAdminRouteImport.update({
    id: '/team-portal/admin',
    path: '/team-portal/admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamPortalApplicantsRoute =
  AuthenticatedTeamPortalApplicantsRouteImport.update({
    id: '/team-portal/applicants',
    path: '/team-portal/applicants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamPortalClientsRoute =
  AuthenticatedTeamPortalClientsRouteImport.update({
    id: '/team-portal/clients',
    path: '/team-portal/clients',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamPortalCorporateRoute =
  AuthenticatedTeamPortalCorporateRouteImport.update({
    id: '/team-portal/corporate',
    path: '/team-portal/corporate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamPortalDashboardRoute =
  AuthenticatedTeamPortalDashboardRouteImport.update({
    id: '/team-portal/dashboard',
    path: '/team-portal/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamPortalReportsRoute =
  AuthenticatedTeamPortalReportsRouteImport.update({
    id: '/team-portal/reports',
    path: '/team-portal/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamPortalSettingsRoute =
  AuthenticatedTeamPortalSettingsRouteImport.update({
    id: '/team-portal/settings',
    path: '/team-portal/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamPortalTeamRoute =
  AuthenticatedTeamPortalTeamRouteImport.update({
    id: '/team-portal/team',
    path: '/team-portal/team',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSetPasswordRoute = ApiAuthSetPasswordRouteImport.update({
  id: '/api/auth/set-password',
  path: '/api/auth/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInRoute = ApiAuthSignInRouteImport.update({
  id: '/api/auth/sign-in',
  path: '/api/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignOutRoute = ApiAuthSignOutRouteImport.update({
  id: '/api/auth/sign-out',
  path: '/api/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamPortalSettingsUsersRoute =
  AuthenticatedTeamPortalSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedTeamPortalSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/apply': typeof ApplyRoute
  '/careers': typeof CareersRouteWithChildren
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/referrals': typeof ReferralsRoute
  '/services': typeof ServicesRouteWithChildren
  '/team-portal': typeof TeamPortalRouteWithChildren
  '/terms': typeof TermsRoute
  '/api/upload-certification': typeof ApiUploadCertificationRoute
  '/careers/apply': typeof CareersApplyRoute
  '/files/$': typeof FilesSplatRoute
  '/services/day-program': typeof ServicesDayProgramRoute
  '/services/residential': typeof ServicesResidentialRoute
  '/services/supported-living': typeof ServicesSupportedLivingRoute
  '/team-portal/set-password': typeof TeamPortalSetPasswordRoute
  '/careers/': typeof CareersIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/team-portal/': typeof TeamPortalIndexRoute
  '/team-portal/account': typeof AuthenticatedTeamPortalAccountRoute
  '/team-portal/admin': typeof AuthenticatedTeamPortalAdminRoute
  '/team-portal/applicants': typeof AuthenticatedTeamPortalApplicantsRoute
  '/team-portal/clients': typeof AuthenticatedTeamPortalClientsRoute
  '/team-portal/corporate': typeof AuthenticatedTeamPortalCorporateRoute
  '/team-portal/dashboard': typeof AuthenticatedTeamPortalDashboardRoute
  '/team-portal/reports': typeof AuthenticatedTeamPortalReportsRoute
  '/team-portal/settings': typeof AuthenticatedTeamPortalSettingsRouteWithChildren
  '/team-portal/team': typeof AuthenticatedTeamPortalTeamRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/set-password': typeof ApiAuthSetPasswordRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/team-portal/settings/users': typeof AuthenticatedTeamPortalSettingsUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/referrals': typeof ReferralsRoute
  '/terms': typeof TermsRoute
  '/api/upload-certification': typeof ApiUploadCertificationRoute
  '/careers/apply': typeof CareersApplyRoute
  '/files/$': typeof FilesSplatRoute
  '/services/day-program': typeof ServicesDayProgramRoute
  '/services/residential': typeof ServicesResidentialRoute
  '/services/supported-living': typeof ServicesSupportedLivingRoute
  '/team-portal/set-password': typeof TeamPortalSetPasswordRoute
  '/careers': typeof CareersIndexRoute
  '/services': typeof ServicesIndexRoute
  '/team-portal': typeof TeamPortalIndexRoute
  '/team-portal/account': typeof AuthenticatedTeamPortalAccountRoute
  '/team-portal/admin': typeof AuthenticatedTeamPortalAdminRoute
  '/team-portal/applicants': typeof AuthenticatedTeamPortalApplicantsRoute
  '/team-portal/clients': typeof AuthenticatedTeamPortalClientsRoute
  '/team-portal/corporate': typeof AuthenticatedTeamPortalCorporateRoute
  '/team-portal/dashboard': typeof AuthenticatedTeamPortalDashboardRoute
  '/team-portal/reports': typeof AuthenticatedTeamPortalReportsRoute
  '/team-portal/settings': typeof AuthenticatedTeamPortalSettingsRouteWithChildren
  '/team-portal/team': typeof AuthenticatedTeamPortalTeamRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/set-password': typeof ApiAuthSetPasswordRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/team-portal/settings/users': typeof AuthenticatedTeamPortalSettingsUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/apply': typeof ApplyRoute
  '/careers': typeof CareersRouteWithChildren
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/referrals': typeof ReferralsRoute
  '/services': typeof ServicesRouteWithChildren
  '/team-portal': typeof TeamPortalRouteWithChildren
  '/terms': typeof TermsRoute
  '/api/upload-certification': typeof ApiUploadCertificationRoute
  '/careers/apply': typeof CareersApplyRoute
  '/files/$': typeof FilesSplatRoute
  '/services/day-program': typeof ServicesDayProgramRoute
  '/services/residential': typeof ServicesResidentialRoute
  '/services/supported-living': typeof ServicesSupportedLivingRoute
  '/team-portal/set-password': typeof TeamPortalSetPasswordRoute
  '/careers/': typeof CareersIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/team-portal/': typeof TeamPortalIndexRoute
  '/_authenticated/team-portal/account': typeof AuthenticatedTeamPortalAccountRoute
  '/_authenticated/team-portal/admin': typeof AuthenticatedTeamPortalAdminRoute
  '/_authenticated/team-portal/applicants': typeof AuthenticatedTeamPortalApplicantsRoute
  '/_authenticated/team-portal/clients': typeof AuthenticatedTeamPortalClientsRoute
  '/_authenticated/team-portal/corporate': typeof AuthenticatedTeamPortalCorporateRoute
  '/_authenticated/team-portal/dashboard': typeof AuthenticatedTeamPortalDashboardRoute
  '/_authenticated/team-portal/reports': typeof AuthenticatedTeamPortalReportsRoute
  '/_authenticated/team-portal/settings': typeof AuthenticatedTeamPortalSettingsRouteWithChildren
  '/_authenticated/team-portal/team': typeof AuthenticatedTeamPortalTeamRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/set-password': typeof ApiAuthSetPasswordRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/_authenticated/team-portal/settings/users': typeof AuthenticatedTeamPortalSettingsUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/apply'
    | '/careers'
    | '/contact'
    | '/privacy'
    | '/programs'
    | '/referrals'
    | '/services'
    | '/team-portal'
    | '/terms'
    | '/api/upload-certification'
    | '/careers/apply'
    | '/files/$'
    | '/services/day-program'
    | '/services/residential'
    | '/services/supported-living'
    | '/team-portal/set-password'
    | '/careers/'
    | '/services/'
    | '/team-portal/'
    | '/team-portal/account'
    | '/team-portal/admin'
    | '/team-portal/applicants'
    | '/team-portal/clients'
    | '/team-portal/corporate'
    | '/team-portal/dashboard'
    | '/team-portal/reports'
    | '/team-portal/settings'
    | '/team-portal/team'
    | '/api/auth/session'
    | '/api/auth/set-password'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/team-portal/settings/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/apply'
    | '/contact'
    | '/privacy'
    | '/programs'
    | '/referrals'
    | '/terms'
    | '/api/upload-certification'
    | '/careers/apply'
    | '/files/$'
    | '/services/day-program'
    | '/services/residential'
    | '/services/supported-living'
    | '/team-portal/set-password'
    | '/careers'
    | '/services'
    | '/team-portal'
    | '/team-portal/account'
    | '/team-portal/admin'
    | '/team-portal/applicants'
    | '/team-portal/clients'
    | '/team-portal/corporate'
    | '/team-portal/dashboard'
    | '/team-portal/reports'
    | '/team-portal/settings'
    | '/team-portal/team'
    | '/api/auth/session'
    | '/api/auth/set-password'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/team-portal/settings/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/accessibility'
    | '/apply'
    | '/careers'
    | '/contact'
    | '/privacy'
    | '/programs'
    | '/referrals'
    | '/services'
    | '/team-portal'
    | '/terms'
    | '/api/upload-certification'
    | '/careers/apply'
    | '/files/$'
    | '/services/day-program'
    | '/services/residential'
    | '/services/supported-living'
    | '/team-portal/set-password'
    | '/careers/'
    | '/services/'
    | '/team-portal/'
    | '/_authenticated/team-portal/account'
    | '/_authenticated/team-portal/admin'
    | '/_authenticated/team-portal/applicants'
    | '/_authenticated/team-portal/clients'
    | '/_authenticated/team-portal/corporate'
    | '/_authenticated/team-portal/dashboard'
    | '/_authenticated/team-portal/reports'
    | '/_authenticated/team-portal/settings'
    | '/_authenticated/team-portal/team'
    | '/api/auth/session'
    | '/api/auth/set-password'
    | '/api/auth/sign-in'
    | '/api/auth/sign-out'
    | '/_authenticated/team-portal/settings/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  ApplyRoute: typeof ApplyRoute
  CareersRoute: typeof CareersRouteWithChildren
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramsRoute: typeof ProgramsRoute
  ReferralsRoute: typeof ReferralsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TeamPortalRoute: typeof TeamPortalRouteWithChildren
  TermsRoute: typeof TermsRoute
  ApiUploadCertificationRoute: typeof ApiUploadCertificationRoute
  FilesSplatRoute: typeof FilesSplatRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiAuthSetPasswordRoute: typeof ApiAuthSetPasswordRoute
  ApiAuthSignInRoute: typeof ApiAuthSignInRoute
  ApiAuthSignOutRoute: typeof ApiAuthSignOutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-portal': {
      id: '/team-portal'
      path: '/team-portal'
      fullPath: '/team-portal'
      preLoaderRoute: typeof TeamPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-certification': {
      id: '/api/upload-certification'
      path: '/api/upload-certification'
      fullPath: '/api/upload-certification'
      preLoaderRoute: typeof ApiUploadCertificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/': {
      id: '/careers/'
      path: '/'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof CareersRoute
    }
    '/careers/apply': {
      id: '/careers/apply'
      path: '/apply'
      fullPath: '/careers/apply'
      preLoaderRoute: typeof CareersApplyRouteImport
      parentRoute: typeof CareersRoute
    }
    '/files/$': {
      id: '/files/$'
      path: '/files/$'
      fullPath: '/files/$'
      preLoaderRoute: typeof FilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/day-program': {
      id: '/services/day-program'
      path: '/day-program'
      fullPath: '/services/day-program'
      preLoaderRoute: typeof ServicesDayProgramRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/residential': {
      id: '/services/residential'
      path: '/residential'
      fullPath: '/services/residential'
      preLoaderRoute: typeof ServicesResidentialRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/supported-living': {
      id: '/services/supported-living'
      path: '/supported-living'
      fullPath: '/services/supported-living'
      preLoaderRoute: typeof ServicesSupportedLivingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/team-portal/': {
      id: '/team-portal/'
      path: '/'
      fullPath: '/team-portal/'
      preLoaderRoute: typeof TeamPortalIndexRouteImport
      parentRoute: typeof TeamPortalRoute
    }
    '/team-portal/set-password': {
      id: '/team-portal/set-password'
      path: '/set-password'
      fullPath: '/team-portal/set-password'
      preLoaderRoute: typeof TeamPortalSetPasswordRouteImport
      parentRoute: typeof TeamPortalRoute
    }
    '/_authenticated/team-portal/account': {
      id: '/_authenticated/team-portal/account'
      path: '/team-portal/account'
      fullPath: '/team-portal/account'
      preLoaderRoute: typeof AuthenticatedTeamPortalAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team-portal/admin': {
      id: '/_authenticated/team-portal/admin'
      path: '/team-portal/admin'
      fullPath: '/team-portal/admin'
      preLoaderRoute: typeof AuthenticatedTeamPortalAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team-portal/applicants': {
      id: '/_authenticated/team-portal/applicants'
      path: '/team-portal/applicants'
      fullPath: '/team-portal/applicants'
      preLoaderRoute: typeof AuthenticatedTeamPortalApplicantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team-portal/clients': {
      id: '/_authenticated/team-portal/clients'
      path: '/team-portal/clients'
      fullPath: '/team-portal/clients'
      preLoaderRoute: typeof AuthenticatedTeamPortalClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team-portal/corporate': {
      id: '/_authenticated/team-portal/corporate'
      path: '/team-portal/corporate'
      fullPath: '/team-portal/corporate'
      preLoaderRoute: typeof AuthenticatedTeamPortalCorporateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team-portal/dashboard': {
      id: '/_authenticated/team-portal/dashboard'
      path: '/team-portal/dashboard'
      fullPath: '/team-portal/dashboard'
      preLoaderRoute: typeof AuthenticatedTeamPortalDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team-portal/reports': {
      id: '/_authenticated/team-portal/reports'
      path: '/team-portal/reports'
      fullPath: '/team-portal/reports'
      preLoaderRoute: typeof AuthenticatedTeamPortalReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team-portal/settings': {
      id: '/_authenticated/team-portal/settings'
      path: '/team-portal/settings'
      fullPath: '/team-portal/settings'
      preLoaderRoute: typeof AuthenticatedTeamPortalSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team-portal/team': {
      id: '/_authenticated/team-portal/team'
      path: '/team-portal/team'
      fullPath: '/team-portal/team'
      preLoaderRoute: typeof AuthenticatedTeamPortalTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/set-password': {
      id: '/api/auth/set-password'
      path: '/api/auth/set-password'
      fullPath: '/api/auth/set-password'
      preLoaderRoute: typeof ApiAuthSetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in': {
      id: '/api/auth/sign-in'
      path: '/api/auth/sign-in'
      fullPath: '/api/auth/sign-in'
      preLoaderRoute: typeof ApiAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-out': {
      id: '/api/auth/sign-out'
      path: '/api/auth/sign-out'
      fullPath: '/api/auth/sign-out'
      preLoaderRoute: typeof ApiAuthSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team-portal/settings/users': {
      id: '/_authenticated/team-portal/settings/users'
      path: '/users'
      fullPath: '/team-portal/settings/users'
      preLoaderRoute: typeof AuthenticatedTeamPortalSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedTeamPortalSettingsRoute
    }
  }
}

interface AuthenticatedTeamPortalSettingsRouteChildren {
  AuthenticatedTeamPortalSettingsUsersRoute: typeof AuthenticatedTeamPortalSettingsUsersRoute
}

const AuthenticatedTeamPortalSettingsRouteChildren: AuthenticatedTeamPortalSettingsRouteChildren =
  {
    AuthenticatedTeamPortalSettingsUsersRoute:
      AuthenticatedTeamPortalSettingsUsersRoute,
  }

const AuthenticatedTeamPortalSettingsRouteWithChildren =
  AuthenticatedTeamPortalSettingsRoute._addFileChildren(
    AuthenticatedTeamPortalSettingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedTeamPortalAccountRoute: typeof AuthenticatedTeamPortalAccountRoute
  AuthenticatedTeamPortalAdminRoute: typeof AuthenticatedTeamPortalAdminRoute
  AuthenticatedTeamPortalApplicantsRoute: typeof AuthenticatedTeamPortalApplicantsRoute
  AuthenticatedTeamPortalClientsRoute: typeof AuthenticatedTeamPortalClientsRoute
  AuthenticatedTeamPortalCorporateRoute: typeof AuthenticatedTeamPortalCorporateRoute
  AuthenticatedTeamPortalDashboardRoute: typeof AuthenticatedTeamPortalDashboardRoute
  AuthenticatedTeamPortalReportsRoute: typeof AuthenticatedTeamPortalReportsRoute
  AuthenticatedTeamPortalSettingsRoute: typeof AuthenticatedTeamPortalSettingsRouteWithChildren
  AuthenticatedTeamPortalTeamRoute: typeof AuthenticatedTeamPortalTeamRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedTeamPortalAccountRoute: AuthenticatedTeamPortalAccountRoute,
  AuthenticatedTeamPortalAdminRoute: AuthenticatedTeamPortalAdminRoute,
  AuthenticatedTeamPortalApplicantsRoute:
    AuthenticatedTeamPortalApplicantsRoute,
  AuthenticatedTeamPortalClientsRoute: AuthenticatedTeamPortalClientsRoute,
  AuthenticatedTeamPortalCorporateRoute: AuthenticatedTeamPortalCorporateRoute,
  AuthenticatedTeamPortalDashboardRoute: AuthenticatedTeamPortalDashboardRoute,
  AuthenticatedTeamPortalReportsRoute: AuthenticatedTeamPortalReportsRoute,
  AuthenticatedTeamPortalSettingsRoute:
    AuthenticatedTeamPortalSettingsRouteWithChildren,
  AuthenticatedTeamPortalTeamRoute: AuthenticatedTeamPortalTeamRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CareersRouteChildren {
  CareersApplyRoute: typeof CareersApplyRoute
  CareersIndexRoute: typeof CareersIndexRoute
}

const CareersRouteChildren: CareersRouteChildren = {
  CareersApplyRoute: CareersApplyRoute,
  CareersIndexRoute: CareersIndexRoute,
}

const CareersRouteWithChildren =
  CareersRoute._addFileChildren(CareersRouteChildren)

interface ServicesRouteChildren {
  ServicesDayProgramRoute: typeof ServicesDayProgramRoute
  ServicesResidentialRoute: typeof ServicesResidentialRoute
  ServicesSupportedLivingRoute: typeof ServicesSupportedLivingRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesDayProgramRoute: ServicesDayProgramRoute,
  ServicesResidentialRoute: ServicesResidentialRoute,
  ServicesSupportedLivingRoute: ServicesSupportedLivingRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface TeamPortalRouteChildren {
  TeamPortalSetPasswordRoute: typeof TeamPortalSetPasswordRoute
  TeamPortalIndexRoute: typeof TeamPortalIndexRoute
}

const TeamPortalRouteChildren: TeamPortalRouteChildren = {
  TeamPortalSetPasswordRoute: TeamPortalSetPasswordRoute,
  TeamPortalIndexRoute: TeamPortalIndexRoute,
}

const TeamPortalRouteWithChildren = TeamPortalRoute._addFileChildren(
  TeamPortalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  ApplyRoute: ApplyRoute,
  CareersRoute: CareersRouteWithChildren,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramsRoute: ProgramsRoute,
  ReferralsRoute: ReferralsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TeamPortalRoute: TeamPortalRouteWithChildren,
  TermsRoute: TermsRoute,
  ApiUploadCertificationRoute: ApiUploadCertificationRoute,
  FilesSplatRoute: FilesSplatRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiAuthSetPasswordRoute: ApiAuthSetPasswordRoute,
  ApiAuthSignInRoute: ApiAuthSignInRoute,
  ApiAuthSignOutRoute: ApiAuthSignOutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
